/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountsPanel: typeof import('./src/components/clientLogFilter/accountsPanel.vue')['default']
    AlgorithmPanel: typeof import('./src/components/clientLogFilter/algorithmPanel.vue')['default']
    BasketPanel: typeof import('./src/components/clientLogFilter/basketPanel.vue')['default']
    ConditionPanel: typeof import('./src/components/clientLogFilter/conditionPanel.vue')['default']
    CopyText: typeof import('./src/components/common/copyText.vue')['default']
    DataPanel: typeof import('./src/components/common/dataPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    FilterPanel: typeof import('./src/components/clientLogFilter/filterPanel.vue')['default']
    FinablePanel: typeof import('./src/components/clientLogFilter/finablePanel.vue')['default']
    FloatingNavigation: typeof import('./src/components/common/FloatingNavigation.vue')['default']
    FundPanel: typeof import('./src/components/clientLogFilter/fundPanel.vue')['default']
    IpoPanel: typeof import('./src/components/clientLogFilter/ipoPanel.vue')['default']
    JsonViewerDialog: typeof import('./src/components/common/JsonViewerDialog.vue')['default']
    LogDetailDialog: typeof import('./src/components/common/LogDetailDialog.vue')['default']
    LogPasteDialog: typeof import('./src/components/common/LogPasteDialog.vue')['default']
    LogStatusPanel: typeof import('./src/components/home/logStatusPanel/index.vue')['default']
    ModuleList: typeof import('./src/components/home/moduleList/index.vue')['default']
    MonacoEditor: typeof import('./src/components/common/MonacoEditor.vue')['default']
    OrderPanel: typeof import('./src/components/clientLogFilter/orderPanel.vue')['default']
    PositionPanel: typeof import('./src/components/clientLogFilter/positionPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticPanel: typeof import('./src/components/clientLogFilter/statisticPanel.vue')['default']
    TradePanel: typeof import('./src/components/clientLogFilter/tradePanel.vue')['default']
  }
}
