# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('api', 'api'),
        ('entity', 'entity'),
        ('utils', 'utils'),
        ('flask_session', 'flask_session'),
        ('__init__.py', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_cors',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'flask_session',
        'pandas',
        'numpy',
        'git',
        'pathlib',
        'json',
        'hashlib',
        'zipfile',
        'shutil',
        'datetime',
        'subprocess',
        'typing',
        'pandas.io.formats.style',
        'pandas.plotting',
        'lxml',
        'lxml.etree',
        'lxml.isoschematron',
        'lxml.objectify',
        'sqlite3',
        'charset_normalizer',
        'dateutil',
        'pytz',
        'six',
        'tomli',
        'wheel',
        'setuptools',
        'importlib_metadata',
        'zipp',
        'jaraco.text',
        'jaraco.functools',
        'jaraco.context',
        'more_itertools',
        'backports.tarfile',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='flask_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
